x-common-log-config: &default_config
  networks:
    - lakehouse
  env_file:
    - .credentials.conf

services:

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    <<: *default_config
    command: server /data --console-address ":9001"
    volumes:
      - lakehouse_minio_vol:/data
      - ../mnt/minio:/data
      - ../mnt/minio/minio-client:/root/.mc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-bucket:
    image: minio/mc:latest
    container_name: minio-bucket
    volumes:
      - .lakehouse-readwrite.json:/policies/lakehouse-readwrite.json
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      until mc alias set myminio http://minio:9000 admin password >/dev/null 2>&1; do
        echo 'Aguardando MinIO...';
        sleep 5;
      done;

      echo 'MinIO está pronto. Iniciando configuração dos buckets.';
      mc mb --ignore-existing myminio/lakehouse;
      echo 'Bucket criado com sucesso.';

      mc anonymous set public myminio/lakehouse;
      echo 'Políticas de acesso definidas para público.';

      mc admin user add myminio airflow airflow123 || true
      mc admin policy remove myminio lakehouse-readwrite || true
      mc admin policy create myminio lakehouse-readwrite /policies/lakehouse-readwrite.json
      mc admin policy attach myminio lakehouse-readwrite --user airflow;

      "
    <<: *default_config
    
  postgres_nessie:
    image: postgres:16
    container_name: postgres_nessie
    <<: *default_config
    environment:
      POSTGRES_USER: nessie
      POSTGRES_PASSWORD: nessie
      POSTGRES_DB: nessie
    volumes:
      - lakehouse_pg_nessie_vol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U nessie"]
      interval: 5s
      timeout: 5s
      retries: 10

  nessie:
    image: ghcr.io/projectnessie/nessie:0.90.4
    container_name: nessie
    restart: always
    depends_on:
      postgres_nessie:
        condition: service_healthy
    environment:
      QUARKUS_HTTP_PORT: "19120"

      NESSIE_VERSION_STORE_TYPE: JDBC
      NESSIE_VERSION_STORE_JDBC_DATABASE: POSTGRES
      NESSIE_VERSION_STORE_JDBC_INIT: "true"

      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres_nessie:5432/nessie
      QUARKUS_DATASOURCE_USERNAME: nessie
      QUARKUS_DATASOURCE_PASSWORD: nessie
    ports:
      - "19120:19120"
    networks:
      - lakehouse

  notebook:
    image: spark-custom:3.5.3
    build: ../docker/notebook
    container_name: notebook
    <<: *default_config
    ports:
      - 8888:8888
    volumes:
      - ../mnt/notebooks:/app
      - ../mnt/src:/app/src/
    environment:
      - NESSIE_URI=http://nessie:19120/api/v2
      - PYTHONPATH=/app/src
      - SPARK_SUBMIT_OPTIONS=--conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.access.key=admin --conf spark.hadoop.fs.s3a.secret.key=password


volumes:
  lakehouse_minio_vol:
  lakehouse_pg_nessie_vol:

networks:
  lakehouse:
    external: true