x-common-log-config: &default_config
  networks:
    - lakehouse_network
  env_file:
    - .credentials.conf

services:

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    <<: *default_config
    command: server /data --console-address ":9001"
    volumes:
      - lakehouse_minio_vol:/data
      - ../mnt/minio:/data
      - ../mnt/minio/minio-client:/root/.mc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-bucket:
    image: minio/mc:latest
    container_name: minio-bucket
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      until mc alias set myminio http://minio:9000 admin password >/dev/null 2>&1; do
        echo 'Aguardando MinIO...';
        sleep 5;
      done;
      echo 'MinIO está pronto. Iniciando configuração dos buckets.';
      mc mb myminio/bronze;
      mc mb myminio/silver;
      mc mb myminio/gold;
      echo 'Buckets criados com sucesso.';
      mc anonymous set public myminio/bronze;
      mc anonymous set public myminio/silver;
      mc anonymous set public myminio/gold;
      echo 'Políticas de acesso definidas para público.';
      "
    <<: *default_config

  postgres_nessie:
    image: postgres:16
    container_name: postgres_nessie
    <<: *default_config
    volumes:
      - lakehouse_pg_nessie_vol:/var/lib/postgresql/data

  nessie:
    image: ghcr.io/projectnessie/nessie:0.105.3-java
    container_name: nessie
    restart: always
    <<: *default_config
    ports:
      - 19120:19120
    depends_on:
      - postgres_nessie

  notebook:
    build: ../docker/notebook
    container_name: notebook
    <<: *default_config
    ports:
      - 8888:8888
    volumes:
      - ../mnt/notebooks:/app/

volumes:
  lakehouse_minio_vol:
  lakehouse_pg_nessie_vol:

networks:
  lakehouse_network:
    driver: bridge