x-common-log-config: &default_config
  networks:
    - lakehouse_network
  env_file:
    - .credentials.conf

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    volumes:
      - ../docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    <<: *default_config

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  
    depends_on:
      - prometheus  
    <<: *default_config
    environment:
      GF_SECURITY_ADMIN_USER=admin
      GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana  

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    <<: *default_config

volumes:
  grafana-storage: 

networks:
  lakehouse_network:
    driver: bridge