x-common-log-config: &default_config
  networks:
    - lakehouse
  env_file:
    - .credentials.conf

services:
  trino:
    image: trinodb/trino:449
    container_name: trino
    ports:
      - "8085:8080"
    volumes:
      - ../docker/trino/etc:/etc/trino
      - ../docker/trino/data:/var/trino/data
    <<: *default_config

  streamlit:
    build:
      context: ../docker/streamlit
      dockerfile: Dockerfile
    container_name: streamlit
    volumes:
      - ../docker/streamlit:/app
    ports:
      - "8501:8501"
    <<: *default_config

networks:
  lakehouse:
    external: true