x-common-log-config: &default_config
  networks:
    - lakehouse_network
  env_file:
    - .credentials.conf

services:
  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8085:8085"
    volumes:
      - ../docker/trino/etc:/etc/trino
    <<: *default_config

  streamlit:
    build:
      context: ../docker/streamlit
      dockerfile: Dockerfile
    container_name: streamlit
    volumes:
      - ../docker/streamlit:/app
    ports:
      - "8501:8501"
    <<: *default_config

networks:
  lakehouse_network:
    driver: bridge