name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r ../mnt/requirements.txt

      - name: Checkar a formatação do codigo
        run: |
          black --check .
          
      - name: Run lint
        run: flake8 .

      - name: Rodar testes com Pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/mnt
          pytest